name: Lint
on:
  pull_request:
    branches:
    - '*'
    tags-ignore:
    - '*'
jobs:
  lint:
    name: PyLint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Packages
      run: pip3 install -r requirements.txt
    - name: Linter
      run: pylint bin/logify
